package aplicacion.modelo.dominio;
// Generated 03/07/2019 16:32:16 by Hibernate Tools 4.3.1



/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private long codigo;
     private Factura factura;
     private Producto producto;
     private Integer cantidad;
     private Double precio;
     private Boolean estado;
     private Double precioTotal;

    public Detalle() {
    }

	
    public Detalle(long codigo, Factura factura, Producto producto) {
        this.codigo = codigo;
        this.factura = factura;
        this.producto = producto;
    }
    public Detalle(long codigo, Factura factura, Producto producto, Integer cantidad, Double precio, Boolean estado, Double precioTotal) {
       this.codigo = codigo;
       this.factura = factura;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precio = precio;
       this.estado = estado;
       this.precioTotal = precioTotal;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Double getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(Double precioTotal) {
        this.precioTotal = precioTotal;
    }




}


