package aplicacion.modelo.dominio;
// Generated 03/07/2019 16:32:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private long codigo;
     private Usuario usuario;
     private Date fecha;
     private Boolean estado;
     private Set detalles = new HashSet(0);

    public Factura() {
    }

	
    public Factura(long codigo) {
        this.codigo = codigo;
    }
    public Factura(long codigo, Usuario usuario, Date fecha, Boolean estado, Set detalles) {
       this.codigo = codigo;
       this.usuario = usuario;
       this.fecha = fecha;
       this.estado = estado;
       this.detalles = detalles;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


