package aplicacion.modelo.dominio;
// Generated 20/06/2019 21:43:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private long codigo;
     private String correo;
     private String password;
     private String nombre;
     private String apellido;
     private Boolean estado;
     private Date fechaNac;
     private Integer dni;
     private String direccion;
     private String barrio;
     private String localidad;
     private Integer telefono;
     private String tipoUsuario;
     private Set facturas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(long codigo) {
        this.codigo = codigo;
    }
    public Usuario(long codigo, String correo, String password, String nombre, String apellido, Boolean estado, Date fechaNac, Integer dni, String direccion, String barrio, String localidad, Integer telefono, String tipoUsuario, Set facturas) {
       this.codigo = codigo;
       this.correo = correo;
       this.password = password;
       this.nombre = nombre;
       this.apellido = apellido;
       this.estado = estado;
       this.fechaNac = fechaNac;
       this.dni = dni;
       this.direccion = direccion;
       this.barrio = barrio;
       this.localidad = localidad;
       this.telefono = telefono;
       this.tipoUsuario = tipoUsuario;
       this.facturas = facturas;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


