package aplicacion.hibernate.mapeos;
// Generated 20/06/2019 21:43:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private long codigo;
     private Factura factura;
     private Producto producto;
     private Integer cantidad;
     private BigDecimal precio;
     private Boolean estado;

    public Detalle() {
    }

	
    public Detalle(Factura factura, Producto producto) {
        this.factura = factura;
        this.producto = producto;
    }
    public Detalle(Factura factura, Producto producto, Integer cantidad, BigDecimal precio, Boolean estado) {
       this.factura = factura;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precio = precio;
       this.estado = estado;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


