package aplicacion.hibernate.mapeos;
// Generated 21/06/2019 19:00:35 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private long codigo;
     private Usuario usuario;
     private Date fecha;
     private Boolean estado;
     private Detalle detalle;

    public Factura() {
    }

	
    public Factura(long codigo) {
        this.codigo = codigo;
    }
    public Factura(long codigo, Usuario usuario, Date fecha, Boolean estado, Detalle detalle) {
       this.codigo = codigo;
       this.usuario = usuario;
       this.fecha = fecha;
       this.estado = estado;
       this.detalle = detalle;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Detalle getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(Detalle detalle) {
        this.detalle = detalle;
    }




}


